permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Alex Barros
url: https://alexbarros.info/informatica_iades
description: Questões de Informática da banca IADES
instagram: ealexbarros
title: Informática - IADES
baseurl: "/informatica_iades"
plugins:
 - github-pages