permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Alex Barros
url: https://alexbarors.info/informatica_iades
description: Questões de Informática da banca IADES
instagram: ealexbarros

plugins:
 - github-pages